// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: demo_proto/demo.proto

package demo_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xpath         string                 `protobuf:"bytes,1,opt,name=xpath,proto3" json:"xpath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_demo_proto_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_demo_proto_demo_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemsRequest) GetXpath() string {
	if x != nil {
		return x.Xpath
	}
	return ""
}

type ValuesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesList) Reset() {
	*x = ValuesList{}
	mi := &file_demo_proto_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesList) ProtoMessage() {}

func (x *ValuesList) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesList.ProtoReflect.Descriptor instead.
func (*ValuesList) Descriptor() ([]byte, []int) {
	return file_demo_proto_demo_proto_rawDescGZIP(), []int{1}
}

func (x *ValuesList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_demo_proto_demo_proto protoreflect.FileDescriptor

const file_demo_proto_demo_proto_rawDesc = "" +
	"\n" +
	"\x15demo_proto/demo.proto\x12\fsysrepo_demo\"'\n" +
	"\x0fGetItemsRequest\x12\x14\n" +
	"\x05xpath\x18\x01 \x01(\tR\x05xpath\"$\n" +
	"\n" +
	"ValuesList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2V\n" +
	"\rSysrepoServer\x12E\n" +
	"\bGetItems\x12\x1d.sysrepo_demo.GetItemsRequest\x1a\x18.sysrepo_demo.ValuesList\"\x00B\x1bZ\x19SysrepoRestAPI/demo_protob\x06proto3"

var (
	file_demo_proto_demo_proto_rawDescOnce sync.Once
	file_demo_proto_demo_proto_rawDescData []byte
)

func file_demo_proto_demo_proto_rawDescGZIP() []byte {
	file_demo_proto_demo_proto_rawDescOnce.Do(func() {
		file_demo_proto_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_proto_demo_proto_rawDesc), len(file_demo_proto_demo_proto_rawDesc)))
	})
	return file_demo_proto_demo_proto_rawDescData
}

var file_demo_proto_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_demo_proto_demo_proto_goTypes = []any{
	(*GetItemsRequest)(nil), // 0: sysrepo_demo.GetItemsRequest
	(*ValuesList)(nil),      // 1: sysrepo_demo.ValuesList
}
var file_demo_proto_demo_proto_depIdxs = []int32{
	0, // 0: sysrepo_demo.SysrepoServer.GetItems:input_type -> sysrepo_demo.GetItemsRequest
	1, // 1: sysrepo_demo.SysrepoServer.GetItems:output_type -> sysrepo_demo.ValuesList
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_proto_demo_proto_init() }
func file_demo_proto_demo_proto_init() {
	if File_demo_proto_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_proto_demo_proto_rawDesc), len(file_demo_proto_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_proto_demo_proto_goTypes,
		DependencyIndexes: file_demo_proto_demo_proto_depIdxs,
		MessageInfos:      file_demo_proto_demo_proto_msgTypes,
	}.Build()
	File_demo_proto_demo_proto = out.File
	file_demo_proto_demo_proto_goTypes = nil
	file_demo_proto_demo_proto_depIdxs = nil
}
