// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: demo_proto/demo.proto

package demo_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysrepoServer_GetItems_FullMethodName = "/sysrepo_demo.SysrepoServer/GetItems"
)

// SysrepoServerClient is the client API for SysrepoServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysrepoServerClient interface {
	GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*ValuesList, error)
}

type sysrepoServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSysrepoServerClient(cc grpc.ClientConnInterface) SysrepoServerClient {
	return &sysrepoServerClient{cc}
}

func (c *sysrepoServerClient) GetItems(ctx context.Context, in *GetItemsRequest, opts ...grpc.CallOption) (*ValuesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValuesList)
	err := c.cc.Invoke(ctx, SysrepoServer_GetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysrepoServerServer is the server API for SysrepoServer service.
// All implementations must embed UnimplementedSysrepoServerServer
// for forward compatibility.
type SysrepoServerServer interface {
	GetItems(context.Context, *GetItemsRequest) (*ValuesList, error)
	mustEmbedUnimplementedSysrepoServerServer()
}

// UnimplementedSysrepoServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysrepoServerServer struct{}

func (UnimplementedSysrepoServerServer) GetItems(context.Context, *GetItemsRequest) (*ValuesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedSysrepoServerServer) mustEmbedUnimplementedSysrepoServerServer() {}
func (UnimplementedSysrepoServerServer) testEmbeddedByValue()                       {}

// UnsafeSysrepoServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysrepoServerServer will
// result in compilation errors.
type UnsafeSysrepoServerServer interface {
	mustEmbedUnimplementedSysrepoServerServer()
}

func RegisterSysrepoServerServer(s grpc.ServiceRegistrar, srv SysrepoServerServer) {
	// If the following call pancis, it indicates UnimplementedSysrepoServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysrepoServer_ServiceDesc, srv)
}

func _SysrepoServer_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysrepoServerServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysrepoServer_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysrepoServerServer).GetItems(ctx, req.(*GetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysrepoServer_ServiceDesc is the grpc.ServiceDesc for SysrepoServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysrepoServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sysrepo_demo.SysrepoServer",
	HandlerType: (*SysrepoServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItems",
			Handler:    _SysrepoServer_GetItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo_proto/demo.proto",
}
